// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherStatus.proto

package bitCask.proto;

public interface WeatherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Weather)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float humidity = 1;</code>
   * @return The humidity.
   */
  float getHumidity();

  /**
   * <code>float temperature = 2;</code>
   * @return The temperature.
   */
  float getTemperature();

  /**
   * <code>float wind_speed = 3;</code>
   * @return The windSpeed.
   */
  float getWindSpeed();
}
