// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherStatus.proto

package bitCask.proto;

public interface WeatherStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.WeatherStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 station_id = 1;</code>
   * @return The stationId.
   */
  long getStationId();

  /**
   * <code>int64 s_no = 2;</code>
   * @return The sNo.
   */
  long getSNo();

  /**
   * <code>string battery_status = 3;</code>
   * @return The batteryStatus.
   */
  String getBatteryStatus();
  /**
   * <code>string battery_status = 3;</code>
   * @return The bytes for batteryStatus.
   */
  com.google.protobuf.ByteString
      getBatteryStatusBytes();

  /**
   * <code>int64 status_timestamp = 4;</code>
   * @return The statusTimestamp.
   */
  long getStatusTimestamp();

  /**
   * <code>.proto.Weather weather = 5;</code>
   * @return Whether the weather field is set.
   */
  boolean hasWeather();
  /**
   * <code>.proto.Weather weather = 5;</code>
   * @return The weather.
   */
  Weather getWeather();
  /**
   * <code>.proto.Weather weather = 5;</code>
   */
  WeatherOrBuilder getWeatherOrBuilder();
}
