// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherStatus.proto

package bitCask.proto;

/**
 * Protobuf type {@code proto.Weather}
 */
public final class Weather extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Weather)
    WeatherOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Weather.newBuilder() to construct.
  private Weather(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Weather() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Weather();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Weather(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            humidity_ = input.readFloat();
            break;
          }
          case 21: {

            temperature_ = input.readFloat();
            break;
          }
          case 29: {

            windSpeed_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return WeatherStatusProto.internal_static_proto_Weather_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return WeatherStatusProto.internal_static_proto_Weather_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Weather.class, Builder.class);
  }

  public static final int HUMIDITY_FIELD_NUMBER = 1;
  private float humidity_;
  /**
   * <code>float humidity = 1;</code>
   * @return The humidity.
   */
  @Override
  public float getHumidity() {
    return humidity_;
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 2;
  private float temperature_;
  /**
   * <code>float temperature = 2;</code>
   * @return The temperature.
   */
  @Override
  public float getTemperature() {
    return temperature_;
  }

  public static final int WIND_SPEED_FIELD_NUMBER = 3;
  private float windSpeed_;
  /**
   * <code>float wind_speed = 3;</code>
   * @return The windSpeed.
   */
  @Override
  public float getWindSpeed() {
    return windSpeed_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (humidity_ != 0F) {
      output.writeFloat(1, humidity_);
    }
    if (temperature_ != 0F) {
      output.writeFloat(2, temperature_);
    }
    if (windSpeed_ != 0F) {
      output.writeFloat(3, windSpeed_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (humidity_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, humidity_);
    }
    if (temperature_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, temperature_);
    }
    if (windSpeed_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, windSpeed_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Weather)) {
      return super.equals(obj);
    }
    Weather other = (Weather) obj;

    if (Float.floatToIntBits(getHumidity())
        != Float.floatToIntBits(
            other.getHumidity())) return false;
    if (Float.floatToIntBits(getTemperature())
        != Float.floatToIntBits(
            other.getTemperature())) return false;
    if (Float.floatToIntBits(getWindSpeed())
        != Float.floatToIntBits(
            other.getWindSpeed())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getHumidity());
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getTemperature());
    hash = (37 * hash) + WIND_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getWindSpeed());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Weather parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Weather parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Weather parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Weather parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Weather parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Weather parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Weather parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Weather parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Weather parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Weather parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Weather parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Weather parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Weather prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Weather}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Weather)
      WeatherOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WeatherStatusProto.internal_static_proto_Weather_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WeatherStatusProto.internal_static_proto_Weather_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Weather.class, Builder.class);
    }

    // Construct using bitCask.proto.Weather.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      humidity_ = 0F;

      temperature_ = 0F;

      windSpeed_ = 0F;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return WeatherStatusProto.internal_static_proto_Weather_descriptor;
    }

    @Override
    public Weather getDefaultInstanceForType() {
      return Weather.getDefaultInstance();
    }

    @Override
    public Weather build() {
      Weather result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Weather buildPartial() {
      Weather result = new Weather(this);
      result.humidity_ = humidity_;
      result.temperature_ = temperature_;
      result.windSpeed_ = windSpeed_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Weather) {
        return mergeFrom((Weather)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Weather other) {
      if (other == Weather.getDefaultInstance()) return this;
      if (other.getHumidity() != 0F) {
        setHumidity(other.getHumidity());
      }
      if (other.getTemperature() != 0F) {
        setTemperature(other.getTemperature());
      }
      if (other.getWindSpeed() != 0F) {
        setWindSpeed(other.getWindSpeed());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Weather parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Weather) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float humidity_ ;
    /**
     * <code>float humidity = 1;</code>
     * @return The humidity.
     */
    @Override
    public float getHumidity() {
      return humidity_;
    }
    /**
     * <code>float humidity = 1;</code>
     * @param value The humidity to set.
     * @return This builder for chaining.
     */
    public Builder setHumidity(float value) {
      
      humidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float humidity = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHumidity() {
      
      humidity_ = 0F;
      onChanged();
      return this;
    }

    private float temperature_ ;
    /**
     * <code>float temperature = 2;</code>
     * @return The temperature.
     */
    @Override
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <code>float temperature = 2;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(float value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float windSpeed_ ;
    /**
     * <code>float wind_speed = 3;</code>
     * @return The windSpeed.
     */
    @Override
    public float getWindSpeed() {
      return windSpeed_;
    }
    /**
     * <code>float wind_speed = 3;</code>
     * @param value The windSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setWindSpeed(float value) {
      
      windSpeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float wind_speed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindSpeed() {
      
      windSpeed_ = 0F;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.Weather)
  }

  // @@protoc_insertion_point(class_scope:proto.Weather)
  private static final Weather DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Weather();
  }

  public static Weather getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Weather>
      PARSER = new com.google.protobuf.AbstractParser<Weather>() {
    @Override
    public Weather parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Weather(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Weather> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Weather> getParserForType() {
    return PARSER;
  }

  @Override
  public Weather getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

