apiVersion: apps/v1
kind: Deployment
metadata:
  name: station5-deployment
  labels:
    app: station5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: station5
  template:
    metadata:
      labels:
        app: station5
    spec:
      containers:
        - name: station5
          image: m13salama/weatherstation:latest
          ports:
            - containerPort: 3000
          env:
            - name: stationNo
              value: "5"
            - name: latitude
              value: "88.6"
            - name: longtitude
              value: "150.7"
            - name: KAFKA_BROKER
              value: kafka-service:9092
          command: ["java", "-jar", "/app/target/weatherStation-1.0.jar", "$(stationNo)", "$(latitude)", "$(longtitude)"]
