apiVersion: apps/v1
kind: Deployment
metadata:
  name: station6-deployment
  labels:
    app: station6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: station6
  template:
    metadata:
      labels:
        app: station6
    spec:
      containers:
        - name: station6
          image: m13salama/weatherstation:latest
          ports:
            - containerPort: 3000
          env:
            - name: stationNo
              value: "6"
            - name: latitude
              value: "-10"
            - name: longtitude
              value: "-20"
            - name: KAFKA_BROKER
              value: kafka-service:9092
          command: ["java", "-jar", "/app/target/weatherStation-1.0.jar", "$(stationNo)", "$(latitude)", "$(longtitude)"]
