// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherStatus.proto

package baseCentralStation.proto;

public final class WeatherStatusProto {
  private WeatherStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_WeatherStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_WeatherStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Weather_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Weather_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023weatherStatus.proto\022\005proto\"\204\001\n\rWeather" +
      "Status\022\022\n\nstation_id\030\001 \001(\003\022\014\n\004s_no\030\002 \001(\003" +
      "\022\026\n\016battery_status\030\003 \001(\t\022\030\n\020status_times" +
      "tamp\030\004 \001(\003\022\037\n\007weather\030\005 \001(\0132\016.proto.Weat" +
      "her\"D\n\007Weather\022\020\n\010humidity\030\001 \001(\002\022\023\n\013temp" +
      "erature\030\002 \001(\002\022\022\n\nwind_speed\030\003 \001(\002B+\n\rbit" +
      "Cask.protoB\022WeatherStatusProtoP\001\242\002\003WSPb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_WeatherStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_WeatherStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_WeatherStatus_descriptor,
        new String[] { "StationId", "SNo", "BatteryStatus", "StatusTimestamp", "Weather", });
    internal_static_proto_Weather_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Weather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Weather_descriptor,
        new String[] { "Humidity", "Temperature", "WindSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
