// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weatherStatus.proto

package baseCentralStation.proto;

/**
 * Protobuf type {@code proto.WeatherStatus}
 */
public final class WeatherStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.WeatherStatus)
        WeatherStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeatherStatus.newBuilder() to construct.
  private WeatherStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeatherStatus() {
    batteryStatus_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new WeatherStatus();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeatherStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            stationId_ = input.readInt64();
            break;
          }
          case 16: {

            sNo_ = input.readInt64();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            batteryStatus_ = s;
            break;
          }
          case 32: {

            statusTimestamp_ = input.readInt64();
            break;
          }
          case 42: {
            Weather.Builder subBuilder = null;
            if (weather_ != null) {
              subBuilder = weather_.toBuilder();
            }
            weather_ = input.readMessage(Weather.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(weather_);
              weather_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return WeatherStatusProto.internal_static_proto_WeatherStatus_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return WeatherStatusProto.internal_static_proto_WeatherStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            WeatherStatus.class, Builder.class);
  }

  public static final int STATION_ID_FIELD_NUMBER = 1;
  private long stationId_;
  /**
   * <code>int64 station_id = 1;</code>
   * @return The stationId.
   */
  @Override
  public long getStationId() {
    return stationId_;
  }

  public static final int S_NO_FIELD_NUMBER = 2;
  private long sNo_;
  /**
   * <code>int64 s_no = 2;</code>
   * @return The sNo.
   */
  @Override
  public long getSNo() {
    return sNo_;
  }

  public static final int BATTERY_STATUS_FIELD_NUMBER = 3;
  private volatile Object batteryStatus_;
  /**
   * <code>string battery_status = 3;</code>
   * @return The batteryStatus.
   */
  @Override
  public String getBatteryStatus() {
    Object ref = batteryStatus_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      batteryStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string battery_status = 3;</code>
   * @return The bytes for batteryStatus.
   */
  @Override
  public com.google.protobuf.ByteString
      getBatteryStatusBytes() {
    Object ref = batteryStatus_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      batteryStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_TIMESTAMP_FIELD_NUMBER = 4;
  private long statusTimestamp_;
  /**
   * <code>int64 status_timestamp = 4;</code>
   * @return The statusTimestamp.
   */
  @Override
  public long getStatusTimestamp() {
    return statusTimestamp_;
  }

  public static final int WEATHER_FIELD_NUMBER = 5;
  private Weather weather_;
  /**
   * <code>.proto.Weather weather = 5;</code>
   * @return Whether the weather field is set.
   */
  @Override
  public boolean hasWeather() {
    return weather_ != null;
  }
  /**
   * <code>.proto.Weather weather = 5;</code>
   * @return The weather.
   */
  @Override
  public Weather getWeather() {
    return weather_ == null ? Weather.getDefaultInstance() : weather_;
  }
  /**
   * <code>.proto.Weather weather = 5;</code>
   */
  @Override
  public WeatherOrBuilder getWeatherOrBuilder() {
    return getWeather();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stationId_ != 0L) {
      output.writeInt64(1, stationId_);
    }
    if (sNo_ != 0L) {
      output.writeInt64(2, sNo_);
    }
    if (!getBatteryStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, batteryStatus_);
    }
    if (statusTimestamp_ != 0L) {
      output.writeInt64(4, statusTimestamp_);
    }
    if (weather_ != null) {
      output.writeMessage(5, getWeather());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stationId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, stationId_);
    }
    if (sNo_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, sNo_);
    }
    if (!getBatteryStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, batteryStatus_);
    }
    if (statusTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, statusTimestamp_);
    }
    if (weather_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getWeather());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof WeatherStatus)) {
      return super.equals(obj);
    }
    WeatherStatus other = (WeatherStatus) obj;

    if (getStationId()
        != other.getStationId()) return false;
    if (getSNo()
        != other.getSNo()) return false;
    if (!getBatteryStatus()
        .equals(other.getBatteryStatus())) return false;
    if (getStatusTimestamp()
        != other.getStatusTimestamp()) return false;
    if (hasWeather() != other.hasWeather()) return false;
    if (hasWeather()) {
      if (!getWeather()
          .equals(other.getWeather())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStationId());
    hash = (37 * hash) + S_NO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSNo());
    hash = (37 * hash) + BATTERY_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getBatteryStatus().hashCode();
    hash = (37 * hash) + STATUS_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStatusTimestamp());
    if (hasWeather()) {
      hash = (37 * hash) + WEATHER_FIELD_NUMBER;
      hash = (53 * hash) + getWeather().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static WeatherStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WeatherStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WeatherStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WeatherStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WeatherStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WeatherStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WeatherStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WeatherStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static WeatherStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static WeatherStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static WeatherStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WeatherStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(WeatherStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.WeatherStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.WeatherStatus)
          WeatherStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WeatherStatusProto.internal_static_proto_WeatherStatus_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WeatherStatusProto.internal_static_proto_WeatherStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WeatherStatus.class, Builder.class);
    }

    // Construct using bitCask.proto.WeatherStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      stationId_ = 0L;

      sNo_ = 0L;

      batteryStatus_ = "";

      statusTimestamp_ = 0L;

      if (weatherBuilder_ == null) {
        weather_ = null;
      } else {
        weather_ = null;
        weatherBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return WeatherStatusProto.internal_static_proto_WeatherStatus_descriptor;
    }

    @Override
    public WeatherStatus getDefaultInstanceForType() {
      return WeatherStatus.getDefaultInstance();
    }

    @Override
    public WeatherStatus build() {
      WeatherStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public WeatherStatus buildPartial() {
      WeatherStatus result = new WeatherStatus(this);
      result.stationId_ = stationId_;
      result.sNo_ = sNo_;
      result.batteryStatus_ = batteryStatus_;
      result.statusTimestamp_ = statusTimestamp_;
      if (weatherBuilder_ == null) {
        result.weather_ = weather_;
      } else {
        result.weather_ = weatherBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof WeatherStatus) {
        return mergeFrom((WeatherStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(WeatherStatus other) {
      if (other == WeatherStatus.getDefaultInstance()) return this;
      if (other.getStationId() != 0L) {
        setStationId(other.getStationId());
      }
      if (other.getSNo() != 0L) {
        setSNo(other.getSNo());
      }
      if (!other.getBatteryStatus().isEmpty()) {
        batteryStatus_ = other.batteryStatus_;
        onChanged();
      }
      if (other.getStatusTimestamp() != 0L) {
        setStatusTimestamp(other.getStatusTimestamp());
      }
      if (other.hasWeather()) {
        mergeWeather(other.getWeather());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      WeatherStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (WeatherStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long stationId_ ;
    /**
     * <code>int64 station_id = 1;</code>
     * @return The stationId.
     */
    @Override
    public long getStationId() {
      return stationId_;
    }
    /**
     * <code>int64 station_id = 1;</code>
     * @param value The stationId to set.
     * @return This builder for chaining.
     */
    public Builder setStationId(long value) {
      
      stationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 station_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStationId() {
      
      stationId_ = 0L;
      onChanged();
      return this;
    }

    private long sNo_ ;
    /**
     * <code>int64 s_no = 2;</code>
     * @return The sNo.
     */
    @Override
    public long getSNo() {
      return sNo_;
    }
    /**
     * <code>int64 s_no = 2;</code>
     * @param value The sNo to set.
     * @return This builder for chaining.
     */
    public Builder setSNo(long value) {
      
      sNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 s_no = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSNo() {
      
      sNo_ = 0L;
      onChanged();
      return this;
    }

    private Object batteryStatus_ = "";
    /**
     * <code>string battery_status = 3;</code>
     * @return The batteryStatus.
     */
    public String getBatteryStatus() {
      Object ref = batteryStatus_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        batteryStatus_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string battery_status = 3;</code>
     * @return The bytes for batteryStatus.
     */
    public com.google.protobuf.ByteString
        getBatteryStatusBytes() {
      Object ref = batteryStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        batteryStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string battery_status = 3;</code>
     * @param value The batteryStatus to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryStatus(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      batteryStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string battery_status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatteryStatus() {
      
      batteryStatus_ = getDefaultInstance().getBatteryStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string battery_status = 3;</code>
     * @param value The bytes for batteryStatus to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      batteryStatus_ = value;
      onChanged();
      return this;
    }

    private long statusTimestamp_ ;
    /**
     * <code>int64 status_timestamp = 4;</code>
     * @return The statusTimestamp.
     */
    @Override
    public long getStatusTimestamp() {
      return statusTimestamp_;
    }
    /**
     * <code>int64 status_timestamp = 4;</code>
     * @param value The statusTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setStatusTimestamp(long value) {
      
      statusTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 status_timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusTimestamp() {
      
      statusTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private Weather weather_;
    private com.google.protobuf.SingleFieldBuilderV3<
            Weather, Weather.Builder, WeatherOrBuilder> weatherBuilder_;
    /**
     * <code>.proto.Weather weather = 5;</code>
     * @return Whether the weather field is set.
     */
    public boolean hasWeather() {
      return weatherBuilder_ != null || weather_ != null;
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     * @return The weather.
     */
    public Weather getWeather() {
      if (weatherBuilder_ == null) {
        return weather_ == null ? Weather.getDefaultInstance() : weather_;
      } else {
        return weatherBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    public Builder setWeather(Weather value) {
      if (weatherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        weather_ = value;
        onChanged();
      } else {
        weatherBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    public Builder setWeather(
        Weather.Builder builderForValue) {
      if (weatherBuilder_ == null) {
        weather_ = builderForValue.build();
        onChanged();
      } else {
        weatherBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    public Builder mergeWeather(Weather value) {
      if (weatherBuilder_ == null) {
        if (weather_ != null) {
          weather_ =
            Weather.newBuilder(weather_).mergeFrom(value).buildPartial();
        } else {
          weather_ = value;
        }
        onChanged();
      } else {
        weatherBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    public Builder clearWeather() {
      if (weatherBuilder_ == null) {
        weather_ = null;
        onChanged();
      } else {
        weather_ = null;
        weatherBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    public Weather.Builder getWeatherBuilder() {
      
      onChanged();
      return getWeatherFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    public WeatherOrBuilder getWeatherOrBuilder() {
      if (weatherBuilder_ != null) {
        return weatherBuilder_.getMessageOrBuilder();
      } else {
        return weather_ == null ?
            Weather.getDefaultInstance() : weather_;
      }
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            Weather, Weather.Builder, WeatherOrBuilder>
        getWeatherFieldBuilder() {
      if (weatherBuilder_ == null) {
        weatherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                Weather, Weather.Builder, WeatherOrBuilder>(
                getWeather(),
                getParentForChildren(),
                isClean());
        weather_ = null;
      }
      return weatherBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.WeatherStatus)
  }

  // @@protoc_insertion_point(class_scope:proto.WeatherStatus)
  private static final WeatherStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new WeatherStatus();
  }

  public static WeatherStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherStatus>
      PARSER = new com.google.protobuf.AbstractParser<WeatherStatus>() {
    @Override
    public WeatherStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeatherStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeatherStatus> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<WeatherStatus> getParserForType() {
    return PARSER;
  }

  @Override
  public WeatherStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

