apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app.kubernetes.io/component: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092