apiVersion: apps/v1
kind: Deployment
metadata:
  name: station3-deployment
  labels:
    app: station3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: station3
  template:
    metadata:
      labels:
        app: station3
    spec:
      containers:
        - name: station3
          image: m13salama/weatherstation:latest
          ports:
            - containerPort: 3000
          env:
            - name: stationNo
              value: "3"
            - name: latitude
              value: "70.6"
            - name: longtitude
              value: "93.7"
            - name: KAFKA_BROKER
              value: kafka-service:9092
          command: ["java", "-jar", "/app/target/Weather-Station-1.0.jar", "$(stationNo)", "$(latitude)", "$(longtitude)"]

